/* File generato automaticamente da build-maxi-data.py — NON modificare a mano.
   Per aggiornare: modifica maxi-impianti.xlsx e ri-lancia AGGIORNA_MAPPA_MAXI.bat */
window.MAXI_IMPIANTI = [
  {
    "code": "NA04",
    "city": "Napoli",
    "pos": "STAZIONE EAV P.ZZA GARIBALDI banchina treni binario 4",
    "type": "Facciata",
    "dim": "1200x300",
    "sqm": 36,
    "light": false,
    "flow": "Stazione Napoli Centrale - Attesa treni",
    "photo": "mx-na-01.jpg",
    "lat": 40.8529176,
    "lng": 14.272529
  },
  {
    "code": "NA05",
    "city": "Napoli",
    "pos": "STAZIONE EAV P.ZZA GARIBALDI banchina treni binario 1",
    "type": "Ponteggio",
    "dim": "1200x300",
    "sqm": 36,
    "light": false,
    "flow": "Stazione Napoli Centrale - Attesa treni",
    "photo": "mx-na-02.jpg",
    "lat": 40.8530043,
    "lng": 14.2730587
  },
  {
    "code": "NA63",
    "city": "Napoli",
    "pos": "VIA MARINA DIREZIONE CENTRO- REGGIA DI PORTICI ANG.GIANTURCO",
    "type": "Muro cieco",
    "dim": "7X10 illuminato",
    "sqm": 70,
    "light": true,
    "flow": "Zona stadio e università",
    "photo": "",
    "lat": 40.8434707,
    "lng": 14.285129
  },
  {
    "code": "NA65",
    "city": "Napoli",
    "pos": "VIA MARINA ALTEZZA INGRESSO AUTOSTRADE",
    "type": "Ponteggio",
    "dim": "7X10 illuminato",
    "sqm": 70,
    "light": true,
    "flow": "~80.000 veicoli/giorno",
    "photo": "",
    "lat": 40.8432079,
    "lng": 14.2857851
  },
  {
    "code": "NA64",
    "city": "Napoli",
    "pos": "VIA G.B.MARINO ang.DE GENNARO DIR.VIA LEPANTO STADIO MARADONA",
    "type": "",
    "dim": "6x6 illuminato",
    "sqm": 36,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8288336,
    "lng": 14.1962536
  },
  {
    "code": "NA66",
    "city": "Napoli",
    "pos": "CORSO ARNALDO LUCCI DIREZ.PIAZZA GARIBALDI",
    "type": "",
    "dim": "7X10 illuminato",
    "sqm": 70,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8479045,
    "lng": 14.2763135
  },
  {
    "code": "NA68",
    "city": "Napoli",
    "pos": "VIA LUIGI VOLPICELLA 413 dir CERCOLA e Paesi Vesuviani",
    "type": "",
    "dim": "7X10 illuminato",
    "sqm": 70,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8483073,
    "lng": 14.3235664
  },
  {
    "code": "NA69",
    "city": "Napoli",
    "pos": "VIA EPOMEO  ROTATORIA DIR.SOCCAVO",
    "type": "",
    "dim": "4x9 illuminato",
    "sqm": 36,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8476009,
    "lng": 14.1913539
  },
  {
    "code": "NA67",
    "city": "Napoli",
    "pos": "VIA TERRACINA stadio Maradona  alt incr  BARBAGALLO dir. AGNANO",
    "type": "",
    "dim": "7X10 illuminato",
    "sqm": 70,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8238497,
    "lng": 14.1774396
  },
  {
    "code": "NA72",
    "city": "Napoli",
    "pos": "VIA PIETRO JACOPO DE GENNARO  ALT.INCR.VIA CARITEO stadio Maradona",
    "type": "",
    "dim": "7x7 illuminato",
    "sqm": 49,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8285001,
    "lng": 14.1973064
  },
  {
    "code": "NA80",
    "city": "Napoli",
    "pos": "VIA DIOCLEZIANO ALT.INC.PIAZZALE TECCHIO DIR.CENTRO",
    "type": "",
    "dim": "5X10 illuminato",
    "sqm": 50,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8227712,
    "lng": 14.1930718
  },
  {
    "code": "NA81",
    "city": "Napoli",
    "pos": "VIALE JF KENNEDY 425  DIR. CENTRO PALAPARTENOPE MOSTRA",
    "type": "",
    "dim": "7X10 illuminato",
    "sqm": 70,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.819075,
    "lng": 14.177719
  },
  {
    "code": "NA83",
    "city": "Napoli",
    "pos": "VIA GABRIELE JANNELLI 304 A MT.80 INC.VIA FRAGNITO",
    "type": "",
    "dim": "8x6 illuminato",
    "sqm": 48,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8590047,
    "lng": 14.2166811
  },
  {
    "code": "NA86",
    "city": "Napoli",
    "pos": "VIA DI MIANO 167 ALT.INC.DON LUIGI GUANELLA",
    "type": "",
    "dim": "5X10 illuminato",
    "sqm": 50,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8900494,
    "lng": 14.2517168
  },
  {
    "code": "NA88",
    "city": "Napoli",
    "pos": "VIA LEPANTO 33 ANG.VIA VENIERO FUORIGROTTA STADIO",
    "type": "",
    "dim": "7X10 illuminato",
    "sqm": 70,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8273596,
    "lng": 14.1986482
  },
  {
    "code": "NA87",
    "city": "Napoli",
    "pos": "VIA EMILIO SCAGLIONE 188",
    "type": "",
    "dim": "7X10 illuminato",
    "sqm": 70,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8829448,
    "lng": 14.2310994
  },
  {
    "code": "NA95",
    "city": "Napoli",
    "pos": "VIA EDGARDO CORTESE ANG.STASI PIAZZA MUZII",
    "type": "",
    "dim": "5X10  illuminato",
    "sqm": 50,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8523986,
    "lng": 14.2299017
  },
  {
    "code": "NA91",
    "city": "Napoli",
    "pos": "VIA FORIA 106 CASERMA GARIBALDI DIR.PIAZZA CARLO III",
    "type": "",
    "dim": "5X8 luminoso",
    "sqm": 40,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8576935,
    "lng": 14.2597536
  },
  {
    "code": "NA92",
    "city": "Napoli",
    "pos": "VIALE DELLA LIBERAZIONE 73 DIR.BAGNOLI",
    "type": "",
    "dim": "7x9 illuminato",
    "sqm": 63,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8206792,
    "lng": 14.1708516
  },
  {
    "code": "NA90",
    "city": "Napoli",
    "pos": "VIA STADERA 138 DIR.CENTRO",
    "type": "",
    "dim": "6X6  illuminato",
    "sqm": 36,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8749357,
    "lng": 14.3059782
  },
  {
    "code": "NA89",
    "city": "Napoli",
    "pos": "VIA EMANUELE GIANTURCO 55 A 50 MT ROTATORIA VIA FERRARIS",
    "type": "",
    "dim": "6x8 illuminato",
    "sqm": 48,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8484328,
    "lng": 14.2885877
  },
  {
    "code": "NA89/96",
    "city": "Napoli",
    "pos": "VIA SANTA MARIA A CUBITO 530 STAZIONE METRO CHIAIANO",
    "type": "",
    "dim": "8X12 illuminato",
    "sqm": 96,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8909184,
    "lng": 14.2226047
  },
  {
    "code": "NA30",
    "city": "Napoli",
    "pos": "VIA NUOVA AGNANO ANGOLO VIALE KENNEDY",
    "type": "",
    "dim": "8X14 illuminato",
    "sqm": 112,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8193127,
    "lng": 14.1751098
  },
  {
    "code": "NA40",
    "city": "Napoli",
    "pos": "VIALE J.F.KENNEDY ANG.VIA NUOVA AGNANO DIR.AGNANO/BAGNOLI",
    "type": "",
    "dim": "8X14 illuminato",
    "sqm": 112,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.819765,
    "lng": 14.175772
  },
  {
    "code": "NA82",
    "city": "Napoli",
    "pos": "VIA TASSO 114 DIR.VOMERO",
    "type": "",
    "dim": "5X10 illuminato",
    "sqm": 50,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8374037,
    "lng": 14.2264429
  },
  {
    "code": "NA70",
    "city": "Napoli",
    "pos": "VIA DIOCLEZIANO 567  DIR. CENTRO",
    "type": "",
    "dim": "5x9 illuminato",
    "sqm": 45,
    "light": true,
    "flow": "",
    "photo": "",
    "lat": 40.8178021,
    "lng": 14.1783744
  }
];
